[package]
name = "libvg"
version = "0.1.0"
authors = ["PJB3005 <pieterjan.briers@gmail.com>"]
publish = false
edition = "2018"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[dependencies]
byond = "0.4.0"
encoding = "0.2.33"

[lib]
name = "libvg"
crate-type = ["cdylib"]
